import type { PageShellModuleConfig } from './page-shell-types'

export const defaultPageShellLayouts: Record<string, PageShellModuleConfig[]> = {
    dashboard: [
        {
            id: 'dashboard-hero',
            type: 'hero',
            title: 'خلاصه وضعیت',
            description: 'نمای کلی از وضعیت امروز سیستم',
            pageKey: 'dashboard',
            size: 'full',
            order: 0,
            hidden: false,
            static: false,
            settings: {
                variant: 'blue',
                primaryText: 'به پنل مدیریت خوش آمدید',
                secondaryText: 'وضعیت کلی سیستم، گزارش‌ها و فعالیت‌ها را اینجا ببینید.',
            },
        },
        {
            id: 'dashboard-stats',
            type: 'stats',
            title: 'شاخص‌های کلیدی',
            description: 'آمار اصلی کسب‌وکار',
            pageKey: 'dashboard',
            size: 'lg',
            order: 1,
            hidden: false,
        },
        {
            id: 'dashboard-chart',
            type: 'chart',
            title: 'روند عملکرد',
            description: 'نمودار رشد و افت',
            pageKey: 'dashboard',
            size: 'xl',
            order: 2,
            hidden: false,
            settings: {
                metric: 'revenue',
            },
        },
        {
            id: 'dashboard-quick-actions',
            type: 'quickActions',
            title: 'دسترسی سریع',
            description: 'عملیات پرکاربرد',
            pageKey: 'dashboard',
            size: 'md',
            order: 3,
            hidden: false,
        },
        {
            id: 'dashboard-activity',
            type: 'activity',
            title: 'فعالیت‌های اخیر',
            description: 'آخرین اتفاقات سیستم',
            pageKey: 'dashboard',
            size: 'lg',
            order: 4,
            hidden: false,
        },
    ],

    reports: [
        {
            id: 'reports-hero',
            type: 'hero',
            title: 'مرکز گزارش‌ها',
            description: 'ساخت، مشاهده و خروجی گرفتن از گزارش‌ها',
            pageKey: 'reports',
            size: 'full',
            order: 0,
            hidden: false,
            settings: {
                variant: 'emerald',
                primaryText: 'گزارش‌های تحلیلی',
                secondaryText: 'گزارش‌های مالی، عملیاتی و مدیریتی را مدیریت کنید.',
            },
        },
        {
            id: 'reports-filters',
            type: 'filters',
            title: 'فیلترهای گزارش',
            description: 'محدوده زمانی و نوع گزارش',
            pageKey: 'reports',
            size: 'full',
            order: 1,
            hidden: false,
        },
        {
            id: 'reports-table',
            type: 'dataTable',
            title: 'لیست گزارش‌ها',
            description: 'آخرین گزارش‌های ساخته‌شده',
            pageKey: 'reports',
            size: 'full',
            order: 2,
            hidden: false,
            permissions: ['reports.read'],
        },
        {
            id: 'reports-chart',
            type: 'chart',
            title: 'تحلیل گزارش‌ها',
            description: 'نمودار وضعیت خروجی‌ها',
            pageKey: 'reports',
            size: 'xl',
            order: 3,
            hidden: false,
        },
    ],

    users: [
        {
            id: 'users-hero',
            type: 'hero',
            title: 'مدیریت کاربران',
            description: 'مدیریت اعضا، نقش‌ها و دسترسی‌ها',
            pageKey: 'users',
            size: 'full',
            order: 0,
            hidden: false,
            settings: {
                variant: 'violet',
                primaryText: 'مدیریت کاربران سازمان',
                secondaryText: 'کاربران، نقش‌ها، وضعیت عضویت و دسترسی‌ها را کنترل کنید.',
            },
        },
        {
            id: 'users-stats',
            type: 'stats',
            title: 'آمار کاربران',
            description: 'تعداد کاربران فعال و غیرفعال',
            pageKey: 'users',
            size: 'lg',
            order: 1,
            hidden: false,
        },
        {
            id: 'users-table',
            type: 'dataTable',
            title: 'لیست کاربران',
            description: 'جدول کاربران سیستم',
            pageKey: 'users',
            size: 'full',
            order: 2,
            hidden: false,
            permissions: ['users.read'],
        },
        {
            id: 'users-activity',
            type: 'activity',
            title: 'فعالیت کاربران',
            description: 'آخرین لاگ‌های مربوط به کاربران',
            pageKey: 'users',
            size: 'lg',
            order: 3,
            hidden: false,
            permissions: ['audit.read'],
        },
    ],
}

export function getDefaultPageShellLayout(pageKey: string) {
    return defaultPageShellLayouts[pageKey] ?? []
}
