import {
    LayoutDashboard,
    BarChart3,
    ClipboardList,
    Receipt,
    Package,
    Tags,
    Users,
    UserRound,
    Gift,
    MessageSquareText,
    Warehouse,
    Truck,
    Store,
    Building2,
    ScanLine,
    Wallet,
    CreditCard,
    Landmark,
    FileText,
    Sparkles,
    Bot,
    Megaphone,
    BellRing,
    PlugZap,
    AppWindow,
    KeyRound,
    Settings,
    ShieldCheck,
    MapPinned,
    Boxes,
    ClipboardCheck,
    AlarmClock,
    BadgeDollarSign,
    ScrollText,
    LineChart,
    PieChart,
    Send,
    Star,
    Cpu,
    Home,
    Bed,
    ClipboardPlus,
    SearchCheck,
    Map,
    CalendarCheck,
    UserCheck,
    Hospital,
    BadgeCheck,
    Route,
    Database,
    FileWarning,
    Network,
} from "lucide-react";

import type { MenuSection } from "./menu.types";
import { APP_BASE_PATH } from "../app-path";

export const MENU_SECTIONS: MenuSection[] = [
    {
        id: "dashboard",
        title: "داشبورد",
        children: [
            {
                id: "dashboard-main",
                title: "داشبورد اصلی",
                type: "item",
                icon: LayoutDashboard,
                path: APP_BASE_PATH + "/dashboard",
                href: APP_BASE_PATH + "/dashboard",
                permission: "dashboard.view",
                exact: true,
                keywords: ["dashboard", "main dashboard", "داشبورد", "اصلی"],
            },
            // {
            //     id: "dashboard-executive",
            //     title: "داشبورد مدیریتی اسکان",
            //     type: "item",
            //     icon: BarChart3,
            //     path: APP_BASE_PATH + "/dashboard/executive",
            //     href: APP_BASE_PATH + "/dashboard/executive",
            //     permission: "dashboard.executive.view",
            //     featureFlag: "executive_dashboard",
            //     badge: { text: "Pro", variant: "premium" },
            //     keywords: ["executive", "shelter analytics", "مدیریتی", "تحلیل ظرفیت"],
            // },
        ],
    },

    {
        id: "request-operations",
        title: "درخواست‌ها و پذیرش",
        children: [
            {
                id: "request-records",
                title: "ثبت و پیگیری درخواست",
                type: "group",
                icon: ClipboardList,
                permission: "shelter.requests.view",
                featureFlag: "shelter_module",
                children: [
                    {
                        id: "requests-all",
                        title: "همه درخواست‌ها",
                        type: "item",
                        path: APP_BASE_PATH + "/shelter/requests",
                        href: APP_BASE_PATH + "/shelter/requests",
                        icon: ClipboardList,
                        permission: "shelter.requests.view",
                        activePaths: [
                            "/shelter/requests/[id]",
                            "/shelter/requests/[id]/review",
                        ],
                        keywords: ["requests", "applications", "درخواست‌ها", "درخواست اسکان"],
                    },
                    {
                        id: "request-new",
                        title: "ثبت درخواست جدید",
                        type: "item",
                        path: APP_BASE_PATH + "/requests/new",
                        href: APP_BASE_PATH + "/requests/new",
                        icon: ClipboardPlus,
                        permission: "requests.create",
                        keywords: ["new request", "application entry", "ثبت درخواست", "درخواست جدید"],
                    },
                    {
                        id: "request-tracking",
                        title: "پیگیری درخواست",
                        type: "item",
                        path: APP_BASE_PATH + "/requests/track",
                        href: APP_BASE_PATH + "/requests/track",
                        icon: SearchCheck,
                        permission: "requests.view",
                        keywords: ["track request", "tracking code", "پیگیری", "کد رهگیری"],
                    },
                    {
                        id: "request-status-history",
                        title: "تاریخچه و سوابق درخواست",
                        type: "item",
                        path: APP_BASE_PATH + "/requests/history",
                        href: APP_BASE_PATH + "/requests/history",
                        icon: Wallet,
                        permission: "requests.view",
                        keywords: ["request history", "records", "سوابق درخواست", "تاریخچه"],
                    },
                ],
            },
            {
                id: "admission-management",
                title: "پذیرش و ارجاع",
                type: "group",
                icon: UserCheck,
                permission: "shelter.reservations.manage",
                featureFlag: "admission",
                children: [
                    {
                        id: "admission-queue",
                        title: "صف بررسی درخواست‌ها",
                        type: "item",
                        path: APP_BASE_PATH + "/shelter/requests",
                        href: APP_BASE_PATH + "/shelter/requests",
                        icon: Package,
                        permission: "shelter.requests.review",
                        keywords: ["admission queue", "review queue", "صف بررسی", "پذیرش"],
                    },
                    {
                        id: "temporary-reservations",
                        title: "رزروهای موقت",
                        type: "item",
                        path: APP_BASE_PATH + "/shelter/reservations",
                        href: APP_BASE_PATH + "/shelter/reservations",
                        icon: CalendarCheck,
                        permission: "shelter.reservations.view",
                        keywords: ["temporary reservation", "booking", "رزرو موقت"],
                    },
                    {
                        id: "referral-management",
                        title: "معرفی‌نامه‌ها و ارجاعات",
                        type: "item",
                        path: APP_BASE_PATH + "/requests/referrals",
                        href: APP_BASE_PATH + "/requests/referrals",
                        icon: Route,
                        permission: "requests.referral.manage",
                        keywords: ["referral", "letter", "معرفی‌نامه", "ارجاع"],
                    },
                ],
            },
        ],
    },

    {
        id: "shelter-capacity-models",
        title: "سراها و ظرفیت اسکان",
        children: [
            {
                id: "shelter-catalog",
                title: "مدیریت سراها",
                type: "group",
                icon: Home,
                permission: "shelters.view",
                featureFlag: "shelter_module",
                children: [
                    {
                        id: "shelters-list",
                        title: "لیست سراهای محله",
                        type: "item",
                        path: APP_BASE_PATH + "/shelter/profiles",
                        href: APP_BASE_PATH + "/shelter/profiles",
                        icon: Building2,
                        permission: "shelters.view",
                        activePaths: [
                            "/shelter/profiles/[id]",
                            "/shelter/profiles/[id]/edit",
                            "/shelter/profiles/new",
                        ],
                        keywords: ["shelters", "neighborhood halls", "سراها", "سرای محله"],
                    },
                    {
                        id: "shelter-categories",
                        title: "دسته‌بندی سراها",
                        type: "item",
                        path: APP_BASE_PATH + "/shelters/categories",
                        href: APP_BASE_PATH + "/shelters/categories",
                        icon: Tags,
                        permission: "shelters.category.manage",
                        keywords: ["shelter categories", "types", "دسته‌بندی سراها"],
                    },
                    {
                        id: "shelter-facilities",
                        title: "امکانات و تجهیزات سرا",
                        type: "item",
                        path: APP_BASE_PATH + "/shelters/facilities",
                        href: APP_BASE_PATH + "/shelters/facilities",
                        icon: Boxes,
                        permission: "shelters.facility.manage",
                        keywords: ["facilities", "equipment", "امکانات", "تجهیزات"],
                    },
                    {
                        id: "shelter-capacity-rules",
                        title: "قواعد ظرفیت و پذیرش",
                        type: "item",
                        path: APP_BASE_PATH + "/shelters/capacity-rules",
                        href: APP_BASE_PATH + "/shelters/capacity-rules",
                        icon: CreditCard,
                        permission: "shelters.capacity.manage",
                        keywords: ["capacity rules", "admission rules", "قواعد ظرفیت", "پذیرش"],
                    },
                ],
            },
            {
                id: "capacity-analysis",
                title: "تحلیل ظرفیت",
                type: "group",
                icon: Bed,
                permission: "capacity.view",
                featureFlag: "shelter_module",
                children: [
                    {
                        id: "capacity-overview",
                        title: "نمای کلی ظرفیت",
                        type: "item",
                        path: APP_BASE_PATH + "/shelter/spaces",
                        href: APP_BASE_PATH + "/shelter/spaces",
                        icon: ScrollText,
                        permission: "shelter.spaces.view",
                        activePaths: [
                            "/shelter/spaces/[id]",
                            "/shelter/spaces/[id]/edit",
                            "/shelter/spaces/new",
                        ],
                        keywords: ["capacity overview", "beds", "نمای ظرفیت", "ظرفیت اسکان"],
                    },
                    {
                        id: "capacity-forecast",
                        title: "پیش‌بینی تکمیل ظرفیت",
                        type: "item",
                        path: APP_BASE_PATH + "/capacity/forecast",
                        href: APP_BASE_PATH + "/capacity/forecast",
                        icon: BadgeDollarSign,
                        permission: "capacity.manage",
                        keywords: ["capacity forecast", "prediction", "پیش‌بینی ظرفیت"],
                    },
                ],
            },
        ],
    },

    {
        id: "map-visualization-service",
        title: "نقشه و نمایش",
        children: [
            {
                id: "shelter-map-management",
                title: "مدیریت نمایش مکانی",
                type: "group",
                icon: Map,
                permission: "map.view",
                children: [
                    {
                        id: "shelter-map",
                        title: "نقشه سراهای فعال",
                        type: "item",
                        path: APP_BASE_PATH + "/shelters/map",
                        href: APP_BASE_PATH + "/shelters/map",
                        icon: MapPinned,
                        permission: "map.view",
                        keywords: ["shelter map", "leaflet", "نقشه سراها", "موقعیت مکانی"],
                    },
                    {
                        id: "capacity-update-queue",
                        title: "صف به‌روزرسانی ظرفیت",
                        type: "item",
                        path: APP_BASE_PATH + "/capacity/update-queue",
                        href: APP_BASE_PATH + "/capacity/update-queue",
                        icon: AlarmClock,
                        permission: "capacity.queue.manage",
                        featureFlag: "capacity_queue",
                        keywords: ["capacity queue", "processing", "صف ظرفیت"],
                    },
                    {
                        id: "inspection-schedule",
                        title: "زمان‌بندی بازدید سراها",
                        type: "item",
                        path: APP_BASE_PATH + "/shelters/inspection-schedule",
                        href: APP_BASE_PATH + "/shelters/inspection-schedule",
                        icon: CalendarCheck,
                        permission: "reservations.view",
                        featureFlag: "reservation",
                        activePaths: [
                            "/shelters/inspection-schedule/[id]",
                            "/shelters/inspection-schedule/[id]/edit",
                        ],
                        keywords: ["shelter inspection", "visit schedule", "بازدید سرا", "زمان‌بندی"],
                    },
                ],
            },
        ],
    },

    // {
    //     id: "decision-support",
    //     title: "پشتیبان تصمیم",
    //     children: [
    //         {
    //             id: "decision-ops",
    //             title: "عملیات تصمیم‌یار",
    //             type: "group",
    //             icon: ShieldCheck,
    //             permission: "decision_support.view",
    //             featureFlag: "decision_support",
    //             children: [
    //                 {
    //                     id: "shelter-status-monitoring",
    //                     title: "پایش وضعیت سراها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/decision-support/status",
    //                     href: APP_BASE_PATH + "/decision-support/status",
    //                     icon: ScanLine,
    //                     permission: "decision_support.view",
    //                     keywords: ["status monitoring", "shelter status", "وضعیت سراها"],
    //                 },
    //                 {
    //                     id: "allocation-planning",
    //                     title: "برنامه تخصیص ظرفیت",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/decision-support/allocation",
    //                     href: APP_BASE_PATH + "/decision-support/allocation",
    //                     icon: ClipboardCheck,
    //                     permission: "decision_support.manage",
    //                     keywords: ["allocation", "capacity allocation", "تخصیص ظرفیت"],
    //                 },
    //                 {
    //                     id: "emergency-accommodation-plan",
    //                     title: "برنامه اسکان اضطراری",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/decision-support/emergency",
    //                     href: APP_BASE_PATH + "/decision-support/emergency",
    //                     icon: Hospital,
    //                     permission: "decision_support.view",
    //                     featureFlag: "emergency_mode",
    //                     keywords: ["emergency shelter", "emergency accommodation", "اسکان اضطراری"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "stakeholders",
    //     title: "کاربران و ذی‌نفعان",
    //     children: [
    //         {
    //             id: "stakeholders-base",
    //             title: "ذی‌نفعان سامانه",
    //             type: "group",
    //             icon: Users,
    //             permission: "applicants.view",
    //             children: [
    //                 {
    //                     id: "applicants-list",
    //                     title: "متقاضیان اسکان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/applicants",
    //                     href: APP_BASE_PATH + "/applicants",
    //                     icon: UserRound,
    //                     permission: "applicants.view",
    //                     activePaths: [
    //                         "/applicants/[id]",
    //                         "/applicants/[id]/edit",
    //                     ],
    //                     keywords: ["applicants", "users", "متقاضیان", "کاربران"],
    //                 },
    //                 {
    //                     id: "partner-organizations",
    //                     title: "سازمان‌های همکار",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/stakeholders/organizations",
    //                     href: APP_BASE_PATH + "/stakeholders/organizations",
    //                     icon: Gift,
    //                     permission: "organizations.view",
    //                     featureFlag: "organizations",
    //                     keywords: ["organizations", "partners", "سازمان‌های همکار"],
    //                 },
    //                 {
    //                     id: "shelter-crm",
    //                     title: "مدیریت ارتباط با متقاضیان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/stakeholders/crm",
    //                     href: APP_BASE_PATH + "/stakeholders/crm",
    //                     icon: Star,
    //                     permission: "crm.view",
    //                     featureFlag: "crm",
    //                     badge: { text: "Pro", variant: "premium" },
    //                     keywords: ["crm", "relations", "ارتباط با متقاضیان"],
    //                 },
    //                 {
    //                     id: "applicant-feedback",
    //                     title: "بازخورد و ارزیابی خدمات",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/stakeholders/feedback",
    //                     href: APP_BASE_PATH + "/stakeholders/feedback",
    //                     icon: MessageSquareText,
    //                     permission: "feedback.view",
    //                     featureFlag: "feedback_system",
    //                     keywords: ["feedback", "evaluation", "بازخورد", "ارزیابی خدمات"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "data-storage-supply",
    //     title: "داده و ذخیره‌سازی",
    //     children: [
    //         {
    //             id: "storage-main",
    //             title: "ذخیره‌سازی داده‌ها",
    //             type: "group",
    //             icon: Database,
    //             permission: "storage.view",
    //             featureFlag: "storage",
    //             children: [
    //                 {
    //                     id: "request-data-storage",
    //                     title: "مخزن داده درخواست‌ها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/data/storage",
    //                     href: APP_BASE_PATH + "/data/storage",
    //                     icon: Warehouse,
    //                     permission: "storage.view",
    //                     keywords: ["request data", "repository", "مخزن داده", "درخواست‌ها"],
    //                 },
    //                 {
    //                     id: "data-validation",
    //                     title: "کنترل و صحت‌سنجی داده",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/data/validation",
    //                     href: APP_BASE_PATH + "/data/validation",
    //                     icon: ClipboardCheck,
    //                     permission: "storage.manage",
    //                     keywords: ["validation", "quality control", "صحت‌سنجی داده"],
    //                 },
    //                 {
    //                     id: "rejected-requests-data",
    //                     title: "داده‌های ناقص و مردود",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/data/rejected",
    //                     href: APP_BASE_PATH + "/data/rejected",
    //                     icon: FileWarning,
    //                     permission: "rejected_data.view",
    //                     featureFlag: "rejected_data_tracking",
    //                     keywords: ["rejected data", "invalid requests", "داده مردود", "درخواست ناقص"],
    //                 },
    //             ],
    //         },
    //         {
    //             id: "data-transfer",
    //             title: "انتقال و تبادل داده",
    //             type: "group",
    //             icon: Network,
    //             permission: "data_transfer.view",
    //             featureFlag: "data_transfer",
    //             children: [
    //                 {
    //                     id: "data-transfer-item",
    //                     title: "انتقال داده سامانه",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/data/transfer",
    //                     href: APP_BASE_PATH + "/data/transfer",
    //                     icon: Truck,
    //                     permission: "data_transfer.view",
    //                     keywords: ["data transfer", "communication", "انتقال داده"],
    //                 },
    //                 {
    //                     id: "data-sources",
    //                     title: "منابع داده",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/data/sources",
    //                     href: APP_BASE_PATH + "/data/sources",
    //                     icon: Store,
    //                     permission: "data_sources.view",
    //                     keywords: ["data sources", "sources", "منابع داده"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "shelter-organization",
    //     title: "سازمان اسکان",
    //     children: [
    //         {
    //             id: "neighborhood-halls",
    //             title: "سراهای محله",
    //             type: "group",
    //             icon: Building2,
    //             permission: "branches.view",
    //             featureFlag: "multi_branch",
    //             children: [
    //                 {
    //                     id: "neighborhood-halls-list",
    //                     title: "لیست سراها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/neighborhood-halls",
    //                     href: APP_BASE_PATH + "/neighborhood-halls",
    //                     icon: Building2,
    //                     permission: "branches.view",
    //                     activePaths: [
    //                         "/neighborhood-halls/[id]",
    //                         "/neighborhood-halls/[id]/edit",
    //                     ],
    //                     keywords: ["neighborhood halls", "shelters", "سراها", "سرای محله"],
    //                 },
    //                 {
    //                     id: "neighborhood-halls-performance",
    //                     title: "عملکرد و وضعیت سراها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/neighborhood-halls/performance",
    //                     href: APP_BASE_PATH + "/neighborhood-halls/performance",
    //                     icon: LineChart,
    //                     permission: "branches.view",
    //                     featureFlag: "advanced_reports",
    //                     keywords: ["shelter performance", "condition", "عملکرد سراها"],
    //                 },
    //             ],
    //         },
    //         {
    //             id: "shelter-staff",
    //             title: "تیم اجرایی سراها",
    //             type: "group",
    //             icon: Users,
    //             permission: "staff.view",
    //             children: [
    //                 {
    //                     id: "shelter-staff-list",
    //                     title: "لیست عوامل اجرایی",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/shelter-staff",
    //                     href: APP_BASE_PATH + "/shelter-staff",
    //                     icon: Users,
    //                     permission: "staff.view",
    //                     activePaths: [
    //                         "/shelter-staff/[id]",
    //                         "/shelter-staff/[id]/edit",
    //                     ],
    //                     keywords: ["staff", "operators", "عوامل اجرایی", "تیم سرا"],
    //                 },
    //                 {
    //                     id: "shelter-staff-attendance",
    //                     title: "حضور و شیفت عوامل",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/shelter-staff/attendance",
    //                     href: APP_BASE_PATH + "/shelter-staff/attendance",
    //                     icon: AlarmClock,
    //                     permission: "attendance.view",
    //                     featureFlag: "hr",
    //                     keywords: ["attendance", "shift", "حضور", "شیفت"],
    //                 },
    //                 {
    //                     id: "shelter-staff-costs",
    //                     title: "هزینه‌های نیروی انسانی",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/shelter-staff/payroll",
    //                     href: APP_BASE_PATH + "/shelter-staff/payroll",
    //                     icon: BadgeDollarSign,
    //                     permission: "payroll.view",
    //                     featureFlag: "payroll",
    //                     keywords: ["human resource cost", "payroll", "هزینه نیروی انسانی"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "finance",
    //     title: "مالی",
    //     children: [
    //         {
    //             id: "finance-main",
    //             title: "مالی و حسابداری اسکان",
    //             type: "group",
    //             icon: Landmark,
    //             permission: "finance.view",
    //             children: [
    //                 {
    //                     id: "shelter-transactions",
    //                     title: "تراکنش‌ها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/finance/transactions",
    //                     href: APP_BASE_PATH + "/finance/transactions",
    //                     icon: Wallet,
    //                     permission: "transactions.view",
    //                     keywords: ["transactions", "shelter finance", "تراکنش"],
    //                 },
    //                 {
    //                     id: "shelter-expenses",
    //                     title: "هزینه‌های سراها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/finance/expenses",
    //                     href: APP_BASE_PATH + "/finance/expenses",
    //                     icon: Receipt,
    //                     permission: "expenses.view",
    //                     keywords: ["expenses", "shelter expenses", "هزینه سراها"],
    //                 },
    //                 {
    //                     id: "shelter-finance-reports",
    //                     title: "گزارش مالی اسکان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/finance/reports",
    //                     href: APP_BASE_PATH + "/finance/reports",
    //                     icon: PieChart,
    //                     permission: "finance.view",
    //                     keywords: ["finance reports", "shelter report", "گزارش مالی"],
    //                 },
    //                 {
    //                     id: "shelter-accounting",
    //                     title: "حسابداری اسکان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/finance/accounting",
    //                     href: APP_BASE_PATH + "/finance/accounting",
    //                     icon: Landmark,
    //                     permission: "accounting.view",
    //                     featureFlag: "accounting",
    //                     badge: { text: "Enterprise", variant: "premium" },
    //                     keywords: ["accounting", "shelter accounting", "حسابداری"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "reports",
    //     title: "گزارشات",
    //     children: [
    //         {
    //             id: "reports-group",
    //             title: "تحلیل و گزارش اسکان",
    //             type: "group",
    //             icon: FileText,
    //             permission: "reports.view",
    //             children: [
    //                 {
    //                     id: "reports-requests",
    //                     title: "گزارش درخواست‌ها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/reports/requests",
    //                     href: APP_BASE_PATH + "/reports/requests",
    //                     icon: BarChart3,
    //                     permission: "reports.view",
    //                     keywords: ["request report", "گزارش درخواست‌ها"],
    //                 },
    //                 {
    //                     id: "reports-capacity",
    //                     title: "گزارش ظرفیت سراها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/reports/capacity",
    //                     href: APP_BASE_PATH + "/reports/capacity",
    //                     icon: Package,
    //                     permission: "reports.view",
    //                     keywords: ["capacity report", "گزارش ظرفیت"],
    //                 },
    //                 {
    //                     id: "reports-applicants",
    //                     title: "گزارش متقاضیان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/reports/applicants",
    //                     href: APP_BASE_PATH + "/reports/applicants",
    //                     icon: Users,
    //                     permission: "reports.view",
    //                     keywords: ["applicants report", "users report", "گزارش متقاضیان"],
    //                 },
    //                 {
    //                     id: "reports-advanced",
    //                     title: "گزارشات پیشرفته",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/reports/advanced",
    //                     href: APP_BASE_PATH + "/reports/advanced",
    //                     icon: LineChart,
    //                     permission: ["reports.view", "reports.export"],
    //                     featureFlag: "advanced_reports",
    //                     badge: { text: "Pro", variant: "premium" },
    //                     keywords: ["advanced reports", "analytics", "گزارشات پیشرفته"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "ai",
    //     title: "هوش مصنوعی",
    //     children: [
    //         {
    //             id: "ai-tools",
    //             title: "ابزارهای هوشمند",
    //             type: "group",
    //             icon: Sparkles,
    //             permission: "ai.view",
    //             featureFlag: "ai_assistant",
    //             children: [
    //                 {
    //                     id: "ai-assistant",
    //                     title: "دستیار هوشمند اسکان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/ai/assistant",
    //                     href: APP_BASE_PATH + "/ai/assistant",
    //                     icon: Bot,
    //                     permission: "ai.view",
    //                     keywords: ["ai assistant", "shelter assistant", "دستیار هوشمند"],
    //                 },
    //                 {
    //                     id: "ai-capacity-forecast",
    //                     title: "پیش‌بینی وضعیت ظرفیت",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/ai/forecast",
    //                     href: APP_BASE_PATH + "/ai/forecast",
    //                     icon: Cpu,
    //                     permission: "ai.view",
    //                     keywords: ["forecast", "capacity forecast", "پیش‌بینی ظرفیت"],
    //                 },
    //                 {
    //                     id: "ai-allocation-suggestions",
    //                     title: "پیشنهادهای تخصیص اسکان",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/ai/suggestions",
    //                     href: APP_BASE_PATH + "/ai/suggestions",
    //                     icon: Sparkles,
    //                     permission: "ai.view",
    //                     keywords: ["allocation suggestions", "پیشنهاد اسکان", "تخصیص ظرفیت"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "communications",
    //     title: "ارتباطات",
    //     children: [
    //         {
    //             id: "shelter-communications",
    //             title: "اطلاع‌رسانی اسکان",
    //             type: "group",
    //             icon: Megaphone,
    //             permission: "communications.view",
    //             children: [
    //                 {
    //                     id: "notification-campaigns",
    //                     title: "کمپین‌های اطلاع‌رسانی",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/communications/campaigns",
    //                     href: APP_BASE_PATH + "/communications/campaigns",
    //                     icon: Send,
    //                     permission: "communications.view",
    //                     featureFlag: "communication_automation",
    //                     keywords: ["campaigns", "notifications", "اطلاع‌رسانی"],
    //                 },
    //                 {
    //                     id: "system-notifications",
    //                     title: "اعلان‌ها",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/communications/notifications",
    //                     href: APP_BASE_PATH + "/communications/notifications",
    //                     icon: BellRing,
    //                     permission: "notifications.view",
    //                     keywords: ["notifications", "alerts", "اعلان"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "integrations",
    //     title: "اتصالات",
    //     children: [
    //         {
    //             id: "integrations-group",
    //             title: "اتصالات و API",
    //             type: "group",
    //             icon: PlugZap,
    //             permission: "integrations.view",
    //             featureFlag: "integrations",
    //             children: [
    //                 {
    //                     id: "integrations-list",
    //                     title: "سرویس‌های متصل",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/integrations",
    //                     href: APP_BASE_PATH + "/integrations",
    //                     icon: AppWindow,
    //                     permission: "integrations.view",
    //                     keywords: ["integrations", "services", "اتصالات"],
    //                 },
    //                 {
    //                     id: "api-keys",
    //                     title: "API Keys",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/integrations/api-keys",
    //                     href: APP_BASE_PATH + "/integrations/api-keys",
    //                     icon: KeyRound,
    //                     permission: "api.view",
    //                     featureFlag: "public_api",
    //                     keywords: ["api keys", "api", "کلید API"],
    //                 },
    //             ],
    //         },
    //     ],
    // },

    // {
    //     id: "settings",
    //     title: "تنظیمات",
    //     children: [
    //         {
    //             id: "settings-group",
    //             title: "پیکربندی",
    //             type: "group",
    //             icon: Settings,
    //             permission: "settings.view",
    //             children: [
    //                 {
    //                     id: "settings-general",
    //                     title: "تنظیمات عمومی سامانه",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/settings/general",
    //                     href: APP_BASE_PATH + "/settings/general",
    //                     icon: Settings,
    //                     permission: "settings.view",
    //                     keywords: ["settings", "general", "تنظیمات عمومی"],
    //                 },
    //                 {
    //                     id: "settings-security",
    //                     title: "امنیت و دسترسی",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/settings/security",
    //                     href: APP_BASE_PATH + "/settings/security",
    //                     icon: ShieldCheck,
    //                     permission: "settings.manage",
    //                     keywords: ["security", "permissions", "امنیت", "دسترسی"],
    //                 },
    //                 {
    //                     id: "settings-capacity",
    //                     title: "تنظیمات ظرفیت و رزرو",
    //                     type: "item",
    //                     path: APP_BASE_PATH + "/settings/capacity",
    //                     href: APP_BASE_PATH + "/settings/capacity",
    //                     icon: BadgeCheck,
    //                     permission: "settings.manage",
    //                     keywords: ["capacity settings", "reservation settings", "تنظیمات ظرفیت", "رزرو"],
    //                 },
    //             ],
    //         },
    //     ],
    // },
];
